name: Java Build with MySQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MySQL_DB_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: csyeDB
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install maven -y

    # Wait for MySQL to start
    - name: Wait for MySQL
      run: |
        echo "Waiting for MySQL to start..."
        sleep 15

    - name: Build with Maven
      run: |
        cd ./csye6225
        mvn clean package test
